name: Build and deploy Bun app to Azure Web App - expense-tracker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun Runtime
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'

      - name: Install dependencies
        run: bun install

      # Only run build and test if the scripts exist
      - name: Check and run build script
        run: |
          if grep -q "\"build\":" package.json; then
            bun run build
          else
            echo "No build script found - skipping build step"
          fi

      - name: Check and run test script
        run: |
          if grep -q "\"test\":" package.json; then
            bun run test
          else
            echo "No test script found - skipping test step"
          fi

      - name: Prepare deployment package
        run: |
          # Create deployment script for Azure
          echo "#!/bin/bash" > startup.sh
          echo "cd /home/site/wwwroot" >> startup.sh
          echo "curl -fsSL https://bun.sh/install | bash" >> startup.sh
          echo "export BUN_INSTALL=\"\$HOME/.bun\"" >> startup.sh
          echo "export PATH=\"\$BUN_INSTALL/bin:\$PATH\"" >> startup.sh
          echo "bun install" >> startup.sh
          echo "bun index.ts" >> startup.sh  # Adjust this line based on your entry point
          chmod +x startup.sh

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: bun-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: bun-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9AF952D0D2BC42B09259BEB946B5404F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_29F894F1802D41259F705B51AD90D576 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C7A17C9B41F048D2ADEE846C6AC1B483 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'expense-tracker'
          slot-name: 'Production'
          package: .
          startup-command: '/home/site/wwwroot/startup.sh'
